### ISSUE TITLE
Why not use curl to download xml?

### ISSUE THREAD

**Issue by ohitworks** [Tom-Mendy/auto_set_bing_wallpaper#1]
Hello Tom,

Thanks for your scripy! It works good on my computer. Except the shell reminds me that wget is not installed. I noticed you use curl to download images, why not use it to download xml as well?

**Comment by ohitworks** [comment]
I open this issue not because I can't solve the problem myself. The main purpose is to thank you for your convenient script. :D I am a new i3 user and am now using your script to configure my wallpaper.

**Comment by Tom-Mendy** [comment]
Thank you, and I will look to implement using curl for this script as well.
